### ISSUE TITLE
Warn or quote automatically in write.taf() when "," in data

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-prod/icesTAF#10]
It would be cool if we could have a line that set quote = TRUE if:

``` r
quote <- any(sapply(x, grepl, pattern = ','))
```
around here might work?

https://github.com/ices-tools-prod/icesTAF/blob/15b9e4347ac024a597ba1ea35e96c5054bf7ed4c/R/write.taf.R#L102-L103

quite a lot of errors come in to peoples scripts due to commas in text strings, especially when moving from write.table and write.csv to write.taf

**Comment by arnima-github** [comment]
Good point, added an informative error message:
721cd7b
