### ISSUE TITLE
Bug in parsing sha code

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-prod/icesTAF#13]
bug is here:
https://github.com/ices-tools-prod/icesTAF/blob/833619df32597cb3d0ba58c2cada4b4b068732ea/R/get.remote.sha.R#L35-L36

in windows at least, n = 2 does nothing.  The url returns a single string, which needs to be parse by a json parser - as in the original pull request:

https://github.com/ices-tools-prod/icesTAF/pull/9/commits/8e2090100de17170a855522aeace52731f711be2

**Comment by arnima-github** [comment]
Fixed in 132e6ba.
