### ISSUE TITLE
Problem with function isFALSE with R < 3.5

### ISSUE THREAD

**Issue by alko989** [ices-tools-prod/icesTAF#5]
The function `isFALSE` was introduced in R version 3.5 but there is no such requirement in the package DESCRIPTION.

I suggest to use `identical(period, FALSE)` in [this line](https://github.com/ices-tools-prod/icesTAF/blob/f09e06633b1439edff4e4553ed3a6c62781d36d9/R/draft.data.R#L90) instead of requiring the latest version of R.

NOTE: I checked the latest R base and `isFALSE` is defined as
`isFALSE <- function(x) is.logical(x) && length(x) == 1L && !is.na(x) && !x`

so another option is to add this line somewhere 
`if(!exists("isFALSE")) isFALSE <- function(x) is.logical(x) && length(x) == 1L && !is.na(x) && !x`

**Comment by arnima-github** [comment]
Great idea, thanks! Fixed in commit 3232994.
