### ISSUE TITLE
Additional functionality in draft.software()

### ISSUE THREAD

**Issue by colinpmillar** [ices-tools-prod/icesTAF#6]
if only `source` is provided, then it is possible to parse the DESCRIPTION and CITATION file to fill in the extra feilds, this means the user can create a SOFTWARE record without installing first:

usage would be:
```r
draft.software(source = "ices-tools-prod/msy@devel")
```
if the user wanted to create an entry that tracked the `devel` branch of the msy package

**Comment by arnima-github** [comment]
Done: 6a92965.
